// Generates src/vars.css from the Aurca design tokens
// Run: node gen-vars.js
const light = {
  surface: '#fcf9f8', 'surface-dim': '#dcd9d9', 'surface-bright': '#fcf9f8',
  'surface-container-lowest': '#ffffff', 'surface-container-low': '#f6f3f2',
  'surface-container': '#f0eded', 'surface-container-high': '#eae7e7',
  'surface-container-highest': '#e4e2e1', 'on-surface': '#2d2e2d',
  'on-surface-variant': '#494d57', 'inverse-surface': '#303030',
  'inverse-on-surface': '#f3f0f0', outline: '#7a776f', 'outline-variant': '#cbc6bd',
  primary: '#a87052', 'on-primary': '#ffffff', 'primary-container': '#f8f6f1',
  'on-primary-container': '#716f6b', 'inverse-primary': '#cac6c1',
  secondary: '#6a5c4d', 'on-secondary': '#ffffff', 'secondary-container': '#e5d7cd',
  'on-secondary-container': '#6f6051', tertiary: '#59614e', 'on-tertiary': '#ffffff',
  'tertiary-container': '#eef7de', 'on-tertiary-container': '#69725d',
  error: '#ba1a1a', 'on-error': '#ffffff', 'error-container': '#ffdad6',
  'on-error-container': '#93000a', 'primary-fixed': '#e6e2dd',
  'primary-fixed-dim': '#cac6c1', 'secondary-fixed': '#f3dfcc',
  'secondary-fixed-dim': '#d6c3b1', 'tertiary-fixed': '#dde6cd',
  background: '#f8f6f1', 'on-background': '#2d2e2d', 'surface-variant': '#e4e2e1',
};
const dark = {
  surface: '#1c1c1c', 'surface-dim': '#141414', 'surface-bright': '#242424',
  'surface-container-lowest': '#141414', 'surface-container-low': '#1a1a1a',
  'surface-container': '#242424', 'surface-container-high': '#2a2a2a',
  'surface-container-highest': '#363636', 'on-surface': '#f0ede8',
  'on-surface-variant': '#9a9690', 'inverse-surface': '#fcf9f8',
  'inverse-on-surface': '#1b1c1c', 'outline-variant': '#363636',
  primary: '#a87052', 'on-primary': '#ffffff', 'primary-container': '#97606C',
  'on-primary-container': '#F8F6F1', 'inverse-primary': '#605e5a',
  'secondary-container': '#97606C', 'on-secondary-container': '#F8F6F1',
  'tertiary-container': '#414937', 'on-tertiary-container': '#eef7de',
  background: '#141414', 'on-background': '#f0ede8', 'surface-variant': '#494D57',
};
// Brand card (Aurca asset kit & figma site) — anchor tokens
const brand = {
  cream: '#F8F6F1',
  'cream-dark': '#E5D7CD',
  beige: '#E5D7CD',
  blush: '#E5D7CD',
  terracotta: '#A87052',
  copper: '#A87052',
  'warm-brown': '#97606C',
  mauve: '#97606C',
  sage: '#494D57',
  slate: '#494D57',
  charcoal: '#494D57',
  dark: '#2D2E2D',
  maroon: '#4A1A28',
  burgundy: '#4A1A28',
  wine: '#472E30',
  silver: '#BCBCBC',
};
const rgb = (hex) => {
  const h = hex.replace('#', '');
  return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16)).join(' ');
};
const lines = (obj) => Object.entries(obj).map(([k, v]) => `  --c-${k}: ${rgb(v)};`).join('\n');
const css = `/* Generated by gen-vars.js — do not edit by hand */
:root {
${lines(light)}
${lines(brand)}
}
.dark {
${lines(dark)}
}
`;
require('fs').writeFileSync(require('path').join(__dirname, 'src/vars.css'), css);
console.log('src/vars.css written');
