// Generates src/vars.css from the HESTIA palettes (light/dark from the Stitch mockups,
// brand constants from hestia/ material-03 brand card). Run: node gen-vars.js
const light = {
  surface: '#fcf9f8', 'surface-dim': '#dcd9d9', 'surface-bright': '#fcf9f8',
  'surface-container-lowest': '#ffffff', 'surface-container-low': '#f6f3f2',
  'surface-container': '#f0eded', 'surface-container-high': '#eae7e7',
  'surface-container-highest': '#e4e2e1', 'on-surface': '#1b1c1c',
  'on-surface-variant': '#494740', 'inverse-surface': '#303030',
  'inverse-on-surface': '#f3f0f0', outline: '#7a776f', 'outline-variant': '#cbc6bd',
  primary: '#605e5a', 'on-primary': '#ffffff', 'primary-container': '#f8f3ee',
  'on-primary-container': '#716f6b', 'inverse-primary': '#cac6c1',
  secondary: '#6a5c4d', 'on-secondary': '#ffffff', 'secondary-container': '#f0dcc9',
  'on-secondary-container': '#6f6051', tertiary: '#59614e', 'on-tertiary': '#ffffff',
  'tertiary-container': '#eef7de', 'on-tertiary-container': '#69725d',
  error: '#ba1a1a', 'on-error': '#ffffff', 'error-container': '#ffdad6',
  'on-error-container': '#93000a', 'primary-fixed': '#e6e2dd',
  'primary-fixed-dim': '#cac6c1', 'secondary-fixed': '#f3dfcc',
  'secondary-fixed-dim': '#d6c3b1', 'tertiary-fixed': '#dde6cd',
  background: '#fcf9f8', 'on-background': '#1b1c1c', 'surface-variant': '#e4e2e1',
};
const dark = {
  surface: '#2D2D2D', 'surface-dim': '#1b1c1c', 'surface-bright': '#3d3d3d',
  'surface-container-lowest': '#363636', 'surface-container-low': '#353535',
  'surface-container': '#3d3d3d', 'surface-container-high': '#454545',
  'surface-container-highest': '#494740', 'on-surface': '#F8F3EE',
  'on-surface-variant': '#cbc6bd', 'inverse-surface': '#fcf9f8',
  'inverse-on-surface': '#1b1c1c', 'outline-variant': '#494740',
  primary: '#F8F3EE', 'on-primary': '#2D2D2D', 'primary-container': '#6F5648',
  'on-primary-container': '#F8F3EE', 'inverse-primary': '#605e5a',
  'secondary-container': '#6F5648', 'on-secondary-container': '#F8F3EE',
  'tertiary-container': '#414937', 'on-tertiary-container': '#eef7de',
  background: '#2D2D2D', 'on-background': '#F8F3EE', 'surface-variant': '#494740',
};
// Brand card (hestia webstite material-03.png) — anchor tokens, identical in both modes
const brand = {
  cream: '#F8F3EE', beige: '#DCC9B6', terracotta: '#C97B63',
  'warm-brown': '#6F5648', sage: '#A9B29B', charcoal: '#2D2D2D',
};
const rgb = (hex) => {
  const h = hex.replace('#', '');
  return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16)).join(' ');
};
const lines = (obj) => Object.entries(obj).map(([k, v]) => `  --c-${k}: ${rgb(v)};`).join('\n');
const css = `/* Generated by gen-vars.js — do not edit by hand */
:root {
${lines(light)}
${lines(brand)}
}
.dark {
${lines(dark)}
}
`;
require('fs').writeFileSync(require('path').join(__dirname, 'src/vars.css'), css);
console.log('src/vars.css written');
